blueprint:
  name: Fenster status -> Heizungssteuerung
  description: |
    Wenn ein oder mehrere Fenster geöffnet werden deaktiviere die Heizung und senke die Zieltemperatur.
    Wenn alle Fenster geschlossen sind aktiviere die Heizung und setze die Zieltemperatur.
  domain: automation
  input:
    window_sensor:
      name: Fenster Sensor
      description: Sensor der das geöffnete Fenster meldet
      selector:
        entity:
          filter:
            - domain: binary_sensor
              device_class: door
            - domain: binary_sensor
              device_class: window
          multiple: true

    thermostat:
      name: Thermostat
      description: Thermostat das geändert werden soll
      selector:
        entity:
          filter:
            - domain: climate
              supported_features:
                - "climate.ClimateEntityFeature.TARGET_TEMPERATURE"
          multiple: true

    target_temp_windows_open:
      name: Temperatur bei geöffnetem Fenster
      description: Zieltemperatur wenn ein Fenster geöffnet ist
      default: 5
      selector:
        number:
          min: 5
          max: 30
          step: 0.5
          unit_of_measurement: °C

    target_temp_windows_closed:
      name: Temperatur bei geschlossenem Fenster
      description: Zieltemperatur wenn alle Fenster geschlossen sind
      default: 21
      selector:
        number:
          min: 5
          max: 30
          step: 0.5
          unit_of_measurement: °C

triggers:
  - trigger: state
    entity_id: !input window_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 30

variables:
  window_entities: !input window_sensor
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {% set open_windows = states | selectattr('entity_id', 'in', window_entities) | selectattr('state', 'eq', 'on') | list %}
              {{ open_windows | length > 0 }}
        sequence:
          - action: climate.set_temperature
            target:
              entity_id: !input thermostat
            data:
              temperature: !input target_temp_windows_open
          - action: climate.turn_off
            target:
              entity_id: !input thermostat
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: !input window_sensor
                state: "off"
        sequence:
          - action: climate.set_temperature
            target:
              entity_id: !input thermostat
            data:
              temperature: !input target_temp_windows_closed
          - action: climate.turn_on
            target:
              entity_id: !input thermostat
