blueprint:
  name: Fenster geöffnet -> Heizung aus
  description: Wenn ein oder mehrere Fenster geöffnet werden deaktiviere die Heizung und senke die Zieltemperatur
  domain: automation
  input:
    window_sensor:
      name: Fenster Sensor
      description: Sensor der das geöffnete Fenster meldet
      selector:
        entity:
          filter:
            - domain: binary_sensor
              device_class: door
            - domain: binary_sensor
              device_class: window
          multiple: true

    thermostat:
      name: Thermostat
      description: Thermostat das deaktiviert werden soll
      selector:
        entity:
          filter:
            - domain: climate
              supported_features:
                - climate.ClimateEntityFeature.TARGET_TEMPERATURE
          multiple: true
triggers:
  - trigger: state
    entity_id: !input window_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 30
    id: window_opened
actions:
  - action: >
      {% if trigger.to_state.state == 'on' %}
        climate.set_temperature = 5
        climate.turn_off
      {% else %}
        climate.set_temperature = 21
        climate.turn_on
      {% endif %}
    target: !input thermostat
